[technote]
id = "SITCOMTN-153"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-153.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-153"
github_default_branch = "main"
date_created = 2025-01-29T15:12:16Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Craig S."
name.family = "Lage"
internal_id = "lagecs"

[[technote.authors.affiliations]]
name = "Physics Department"
internal_id = "UCDavis"
address = "University of California, One Shields Avenue, Davis, CA 95616, USA"
